# Zadanie 12

In [46]:
import numpy as np


def plut_from_mixture(probabilities, luts):
    probabilities = np.array(probabilities)
    luts = np.array(luts)

    probabilities = probabilities[:, np.newaxis]
    mixed_array = np.sum(probabilities * luts, axis=0)

    return mixed_array


def mixture_from_plut(plut):
    plut = np.asarray(plut)
    pi = np.array([1 - plut, plut])
    probabilities = []
    luts = []

    while not np.isclose(np.sum(pi), 0):
        max_in_columns = np.max(pi, axis=0)
        alpha = min(max_in_columns)
        l = np.zeros_like(pi)

        for i, max_val in enumerate(max_in_columns):
            idx = np.where(pi[:, i] == max_val)[0][0]
            l[idx, i] = 1

        pi = pi - alpha * l

        probabilities.append(alpha)
        luts.append(list(l[1]))

    return np.round(probabilities, 5), np.round(luts)


In [51]:
plut_from_mixture([0.7, 0.3], [[1, 0, 1, 0, 1, 0, 1, 0], [0, 0, 0, 0, 0, 0, 1, 1]])

array([0.7, 0. , 0.7, 0. , 0.7, 0. , 1. , 0.3])

In [52]:
mixture_from_plut([1, 0.9, 0.75, 0.4, 0.5, 1, 0, 0.2])

(array([0.5 , 0.25, 0.15, 0.05, 0.05]),
 array([[1., 1., 1., 0., 0., 1., 0., 0.],
        [1., 1., 0., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 1.],
        [1., 0., 1., 0., 1., 1., 0., 0.],
        [1., 0., 1., 0., 1., 1., 0., 1.]]))